[package]
name = "dy-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = { workspace = true }
sycamore = { workspace = true }
thiserror = { workspace = true }

dy-macro = { workspace = true }